apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudevents-webui.fullname" . }}-messenger
  labels:
    {{- include "cloudevents-webui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cloudevents-webui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cloudevents-webui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloudevents-webui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-php
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}
          command:
            - 'bin/console'
            - 'messenger:consume'
            - '-vv'
            - 'async'
          env:
            - name: SERVER_NAME
              value: :80
            - name: PWA_UPSTREAM
              value: {{ include "cloudevents-webui.fullname" . }}-pwa:3000
            - name: MERCURE_PUBLISHER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: mercure-jwt-secret
            - name: MERCURE_SUBSCRIBER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: mercure-jwt-secret
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: php-trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: php-trusted-proxies
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: php-app-env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: php-app-debug
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: php-app-secret
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: php-cors-allow-origin
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: database-url
            - name: CADDY_GLOBAL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: caddy-global-options
            - name: MERCURE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: mercure-url
            - name: MERCURE_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: mercure-public-url
            - name: MERCURE_EXTRA_DIRECTIVES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: mercure-extra-directives
            - name: MERCURE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloudevents-webui.fullname" . }}
                  key: mercure-jwt-secret
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: admin
              containerPort: 2019
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "/bin/ps -ef | grep messenger:consume | grep -v grep"]
            initialDelaySeconds: 15
            periodSeconds: 3
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "/bin/ps -ef | grep messenger:consume | grep -v grep"]
            initialDelaySeconds: 60
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
