apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: cloudevents-webui
build:
  artifacts:
    - image: cloudevents-webui-php
      context: ../api
      docker:
        target: app_php
    - image: cloudevents-webui-pwa
      context: ../pwa
      docker:
        target: prod

deploy:
  kubeContext: minikube
  helm:
    releases:
    - name: cloudevents-webui
      chartPath: ./cloudevents-webui
      namespace: default
      setValueTemplates:
        php.image.repository: "{{.IMAGE_REPO_api_platform_php}}"
        php.image.tag: "{{.IMAGE_TAG_api_platform_php}}@{{.IMAGE_DIGEST_api_platform_php}}"
        pwa.image.repository: "{{.IMAGE_REPO_api_platform_pwa}}"
        pwa.image.tag: "{{.IMAGE_TAG_api_platform_pwa}}@{{.IMAGE_DIGEST_api_platform_pwa}}"
      valuesFiles:
        - skaffold-values.yaml
